<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #1a1a1a; font-size: 12px; margin: 0; }
        .wrap { padding: 32px 40px; }
        .header { border-bottom: 2px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 20px; }
        .brand { font-size: 22px; font-weight: bold; }
        .muted { color: #636363; }
        .row { width: 100%; }
        .row td { vertical-align: top; }
        h1 { font-size: 16px; margin: 0 0 4px; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 16px; }
        table.items th { text-align: left; border-bottom: 1px solid #1a1a1a; padding: 8px 6px; font-size: 11px; }
        table.items td { padding: 8px 6px; border-bottom: 1px solid #ececec; }
        .right { text-align: right; }
        .totals { width: 240px; float: right; margin-top: 14px; }
        .totals td { padding: 4px 6px; }
        .totals .grand { border-top: 1px solid #1a1a1a; font-weight: bold; font-size: 14px; }
        .badge { display: inline-block; padding: 3px 10px; border-radius: 10px; font-size: 11px; background: #f8f7f5; }
        .footer { margin-top: 60px; color: #636363; font-size: 10px; text-align: center; }
    </style>
</head>
<body>
<div class="wrap">
    <div class="header">
        <table class="row">
            <tr>
                <td><span class="brand">AfriChart EMR</span></td>
                <td class="right">
                    <h1>INVOICE</h1>
                    <div class="muted">{{ $invoice->invoice_number }}</div>
                    <div class="muted">{{ $invoice->created_at->format('j F Y') }}</div>
                </td>
            </tr>
        </table>
    </div>

    <table class="row">
        <tr>
            <td>
                <div class="muted">Billed To</div>
                <strong>{{ $invoice->patient?->full_name }}</strong><br>
                <span class="muted">{{ $invoice->patient?->patient_id }}</span><br>
                <span class="muted">{{ $invoice->patient?->phone }}</span>
            </td>
            <td class="right">
                <div class="muted">Status</div>
                <span class="badge">{{ $invoice->status->label() }}</span>
                @if ($invoice->consultation)
                    <div class="muted" style="margin-top:8px;">Consultation</div>
                    {{ $invoice->consultation->consultation_id }}
                @endif
            </td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th>#</th>
                <th>Description</th>
                <th class="right">Unit Price</th>
                <th class="right">Qty</th>
                <th class="right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($invoice->items as $i => $item)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $item->description }}</td>
                    <td class="right">&#8358;{{ number_format((float) $item->unit_price, 2) }}</td>
                    <td class="right">{{ $item->quantity }}</td>
                    <td class="right">&#8358;{{ number_format((float) $item->amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals">
        <tr><td class="muted">Subtotal</td><td class="right">&#8358;{{ number_format((float) $invoice->subtotal, 2) }}</td></tr>
        <tr><td class="muted">Tax</td><td class="right">&#8358;{{ number_format((float) $invoice->tax, 2) }}</td></tr>
        <tr><td class="muted">Discount</td><td class="right">&#8358;{{ number_format((float) $invoice->discount, 2) }}</td></tr>
        <tr class="grand"><td>Total</td><td class="right">&#8358;{{ number_format((float) $invoice->total, 2) }}</td></tr>
    </table>

    <div style="clear:both;"></div>

    @if ($invoice->status === \App\Enums\InvoiceStatus::Paid)
        <p class="muted" style="margin-top:24px;">
            Paid via {{ $invoice->payment_method?->label() }} on {{ $invoice->paid_at?->format('j F Y') }}.
        </p>
    @endif

    <div class="footer">
        Generated by AfriChart EMR · {{ $invoice->createdBy?->name }} · {{ now()->format('j F Y, g:i A') }}
    </div>
</div>
</body>
</html>
